# Generated by Django 4.2.3 on 2023-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='blog title')),
                ('plot', models.TextField(max_length=500, verbose_name='blog description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='blog slug')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['date', 'title'],
            },
        ),
    ]
